framework:
    secret: secret

snc_redis:
    clients:
        busque:
            type: predis
            alias: busque
            dsn: 'redis://localhost'
            logging: false
            options:
                profile: 2.6
