framework:
    secret: secret

snc_redis:
    clients:
        busque:
            type: phpredis
            alias: busque
            dsn: 'redis://redis'
            options:
                connection_persistent: true
                connection_timeout: 120
                read_write_timeout: 120
                profile: 3.2
